# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m90XG-aDBeqe3PtvPx2ZVZMysA_CUrCH
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from modul import NamaClass
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    confusion_matrix, ConfusionMatrixDisplay, classification_report
)

df = pd.read_csv('diabetes_prediction_dataset.csv')

df.head()

df.info()

label_encoder = LabelEncoder()

df['gender'] = label_encoder.fit_transform(df['gender'])
df['smoking_history'] = label_encoder.fit_transform(df['smoking_history'])

X = df.drop('diabetes', axis=1)
y = df['diabetes']

df.dropna(inplace=True)
X = df.drop('diabetes', axis=1)
y = df['diabetes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=2022,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("=== Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

accuracy_lr = accuracy_score(y_test, y_pred_lr)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Perbandingan Akurasi:")
print("Logistic Regression :", accuracy_lr)
print("Random Forest       :", accuracy_rf)

# Contoh data pasien baru
data_baru = np.array([[
    1,      # gender (Male=1, Female=0)
    45,     # age
    0,      # hypertension
    0,      # heart_disease
    2,      # smoking_history (hasil encoding)
    28.5,   # bmi
    6.1,    # HbA1c_level
    150     # blood_glucose_level
]])

# Normalisasi
data_baru = scaler.transform(data_baru)

# Prediksi
hasil = rf_model.predict(data_baru)

if hasil[0] == 1:
    print("Pasien TERDETEKSI diabetes")
else:
    print("Pasien TIDAK terdeteksi diabetes")

st.set_page_config(
    page_title="Diabetes Prediction App",
    layout="wide"
)

@st.cache_data
def load_data():
    return pd.read_csv("diabetes_prediction_dataset.csv")

df = load_data()

st.sidebar.title("📌 Navigation")
menu = st.sidebar.radio(
    "Go to",
    ["Overview", "EDA", "Modeling", "Prediction"]
)

X = df.drop("diabetes", axis=1)
y = df["diabetes"]

X = pd.get_dummies(X, drop_first=True)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

if menu == "Overview":
    st.title("🩺 Diabetes Prediction App")
    st.write("""
    Sistem ini dikembangkan untuk mendeteksi penyakit diabetes
    menggunakan pendekatan machine learning berbasis data kesehatan.
    """)

if menu == "EDA":
    st.header("📊 Exploratory Data Analysis")

    st.subheader("Preview Dataset")
    st.dataframe(df.head())

    st.subheader("Distribusi Diabetes")
    fig, ax = plt.subplots()
    df["diabetes"].value_counts().plot(kind="bar", ax=ax)
    st.pyplot(fig)

    st.subheader("Korelasi Antar Fitur")
    corr = df.corr(numeric_only=True)

    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(corr, cmap="coolwarm")

    ax.set_xticks(range(len(corr.columns)))
    ax.set_yticks(range(len(corr.columns)))
    ax.set_xticklabels(corr.columns, rotation=90)
    ax.set_yticklabels(corr.columns)

    plt.colorbar(im)
    st.pyplot(fig)


    st.info("📌 Insight: Data menunjukkan ketidakseimbangan kelas.")

if menu == "Modeling":
    st.header("🤖 Machine Learning Modeling")

    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Random Forest": RandomForestClassifier(random_state=42)
    }

    for name, model in models.items():
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

        col1, col2, col3 = st.columns(3)
        col1.metric("Accuracy", accuracy_score(y_test, preds))
        col2.metric("Precision", precision_score(y_test, preds))
        col3.metric("Recall", recall_score(y_test, preds))

        fig, ax = plt.subplots()
        ConfusionMatrixDisplay(confusion_matrix(y_test, preds)).plot(ax=ax)
        st.pyplot(fig)

if menu == "Prediction":
    st.header("🧪 Diabetes Prediction")

    with st.form("prediction_form"):
        age = st.number_input("Age", 1, 100, 30)
        bmi = st.number_input("BMI", 10.0, 60.0, 25.0)
        glucose = st.number_input("Blood Glucose Level", 50, 300, 120)
        submit = st.form_submit_button("Predict")

    if submit:
        input_df = pd.DataFrame(
            [[age, bmi, glucose]],
            columns=["age", "bmi", "blood_glucose_level"]
        )
        input_scaled = scaler.transform(input_df)

        model = RandomForestClassifier(random_state=42)
        model.fit(X_train, y_train)
        prediction = model.predict(input_scaled)

        st.success("✅ Tidak Diabetes" if prediction[0] == 0 else "⚠️ Berpotensi Diabetes")

st.markdown("""
### Insights:
- Blood glucose dan HbA1c memiliki pengaruh besar terhadap diabetes
- BMI dan usia meningkatkan risiko diabetes
- Dataset layak digunakan untuk klasifikasi ML
""")

# Cell 5: Data Preprocessing

st.header("3️⃣ Data Preprocessing")

X = df.drop("diabetes", axis=1)
y = df["diabetes"]

# Encoding fitur kategorikal
X = pd.get_dummies(X, drop_first=True)

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Cell 6: Machine Learning Modeling

st.header("4️⃣ Machine Learning Modeling")

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

st.subheader("Model Performance")
st.write("Accuracy:", accuracy_score(y_test, y_pred))
st.text("Classification Report:")
st.text(classification_report(y_test, y_pred))

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)

st.write(f"🔹 Random Forest Accuracy: **{rf_acc:.4f}**")

fig, ax = plt.subplots()
models = ["Logistic Regression", "Random Forest"]
accuracy = [lr_acc, rf_acc]

sns.barplot(x=models, y=accuracy, ax=ax)
ax.set_ylim(0,1)
st.pyplot(fig)

st.markdown("""
### Recommendation
✅ Random Forest direkomendasikan karena memiliki performa akurasi yang lebih tinggi dan stabil.
""")

# Cell 7: Prediction Form

st.header("5️⃣ Coba Prediksi Diabetes")

with st.form("prediction_form"):
    age = st.number_input("Age", 1, 100, 30)
    bmi = st.number_input("BMI", 10.0, 60.0, 25.0)
    glucose = st.number_input("Blood Glucose Level", 50, 300, 120)

    submitted = st.form_submit_button("Predict")

if submitted:
    input_data = pd.DataFrame(
        [[age, bmi, glucose]],
        columns=["age", "bmi", "blood_glucose_level"]
    )

    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Berpotensi Diabetes")
    else:
        st.success("✅ Tidak Diabetes")

if submit:
    input_data = np.array([[
        1 if gender == "Male" else 0,
        age, hypertension, heart_disease,
        smoking, bmi, hba1c, glucose
    ]])

    input_data = scaler.transform(input_data)
    result = rf_model.predict(input_data)

    if result[0] == 1:
        st.error("⚠️ TERDETEKSI DIABETES")
    else:
        st.success("✅ TIDAK TERDETEKSI DIABETES")

